USE [master]
GO

/****** Object:  Database [MeusJogosBD]    Script Date: 22/02/2018 01:34:59 ******/
CREATE DATABASE [MeusJogosBD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MeusJogosBD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\MeusJogosBD.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MeusJogosBD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\MeusJogosBD_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MeusJogosBD] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MeusJogosBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MeusJogosBD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MeusJogosBD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MeusJogosBD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MeusJogosBD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MeusJogosBD] SET ARITHABORT OFF 
GO

ALTER DATABASE [MeusJogosBD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MeusJogosBD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MeusJogosBD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MeusJogosBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MeusJogosBD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MeusJogosBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MeusJogosBD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MeusJogosBD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MeusJogosBD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MeusJogosBD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MeusJogosBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MeusJogosBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MeusJogosBD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MeusJogosBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MeusJogosBD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MeusJogosBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MeusJogosBD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MeusJogosBD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MeusJogosBD] SET  MULTI_USER 
GO

ALTER DATABASE [MeusJogosBD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MeusJogosBD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MeusJogosBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MeusJogosBD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MeusJogosBD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MeusJogosBD] SET  READ_WRITE 
GO


